### ISSUE TITLE
error using webtrees 2.0.10

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-mtv#1]
I just installed this module under webtrees 2.0.10, but got an error:
`
ErrorException: file(/mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/huhwt-mtv/resources/lang/de/messages.po): failed to open stream: No such file or directory in /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/fisharebest/localization/src/Translation.php:56 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'file(/mnt/web31...', '/mnt/web312/a3/...', 56, Array) #1 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/fisharebest/localization/src/Translation.php(56): file('/mnt/web312/a3/...') #2 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/modules_v4/huhwt-mtv/MultTreeView.php(138): Fisharebest\Localization\Translation->__construct('/mnt/web312/a3/...') #3 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/I18N.php(316): HuHwt\WebtreesMods\MultTreeView->customTranslations('de') #4 [internal function]: Fisharebest\Webtrees\I18N::Fisharebest\Webtrees\{closure}(Array, Object(HuHwt\WebtreesMods\MultTreeView)) #5 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/illuminate/support/Collection.php(1512): array_reduce(Array, Object(Closure), Array) #6 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/I18N.php(315): Illuminate\Support\Collection->reduce(Object(Closure), Array) #7 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/UseLanguage.php(67): Fisharebest\Webtrees\I18N::init('de') #8 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #9 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/UseSession.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #10 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #11 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(58): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #12 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #13 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/UseDebugbar.php(67): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #14 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDebugbar->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #15 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/UseDatabase.php(117): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #16 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #17 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/app/Http/Middleware/BadBotBlocker.php(212): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #18 /mnt/web312/a3/99/51547399/htdocs/hermann/hartenthaler/php/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #19
`

**Comment by huhwt** [comment]
Sorry, is my first attempt to create a mod ... the learning curve is quite steep :(. Had the software at the time only running under localhost and dev environment and simply stumbled into all possible traps when bundling and gitting.
Now it runs on a real web server and purly based on the git release. Would be happy if you would give the mod another chance.
With best regards
EW.H

**Comment by hartenthaler** [comment]
Nice module! I like it! But it was not obvious for me where I can find it. Maybe a more specific hint in README could help: "Control panel / Manage family trees / Find duplicates".
