### ISSUE TITLE
modified language handling results in no translation

### ISSUE THREAD

**Issue by TheDutchJewel** [huhwt/huhwt-mtv#12]
After the update to v1.2.2 (with modified language handling) the translation no longer works: all text is in English only.

The problem can be fixed by changing this line in the **MultTreeView.php** file:

`$languageFile = $this->resourcesFolder() . 'lang/' . $_language . '.po';`

into:

`$languageFile = $this->resourcesFolder() . 'lang/' . $language . '/messages.po';`

**Comment by huhwt** [comment]
Done.

**Comment by TheDutchJewel** [comment]
> Done

Are you sure? It's not fixed in 2.1.1.0.2.
