### ISSUE TITLE
Control panel / Manage family trees / Find duplicates: numbers instead of the bullets

### ISSUE THREAD

**Issue by TheDutchJewel** [huhwt/huhwt-mtv#14]
In **Control panel / Manage family trees / Find duplicates** webtrees uses numbers for each duplicated item:

![afbeelding](https://user-images.githubusercontent.com/46184729/147595109-0368e210-eee9-4396-9346-8453a4ecdd41.png)

But the ℍ&ℍwt MultTreeView module replaces the numbers with bullets:

![afbeelding](https://user-images.githubusercontent.com/46184729/147595133-36a9f26b-4791-426f-8632-72877d65341d.png)

Is it possible to show numbers instead of the bullets?

**Comment by huhwt** [comment]
Style of Duplicates list is now changed - former unordered, now ordered list ...
