### ISSUE TITLE
2.1.1.0 - Call to undefined method Fisharebest\Webtrees\Age::ageAtEvent()

### ISSUE THREAD

**Issue by TheDutchJewel** [huhwt/huhwt-mtv#17]
I tried huhwt-mtv 2.1.1.0 with webtrees 2.1.2 and 2.1.4 without any other module, but on both versions I get this error:
![afbeelding](https://user-images.githubusercontent.com/46184729/169684181-f9e754c9-2a7a-496a-b5af-1d688afeff18.png)

**Comment by huhwt** [comment]
Thanks for the quick response! Fixed.
