### ISSUE TITLE
Module causing an error in Webtrees 2.1

### ISSUE THREAD

**Issue by geugeu1** [huhwt/huhwt-mtv#20]
Module causing an error in Webtrees 2.1.4

**Comment by huhwt** [comment]
??? What kind of error?

**Comment by geugeu1** [comment]
ErrorException: filemtime(): stat failed for /homepages/20/d313131269/htdocs/webtrees/modules_v4/huhwt-mtv-master/resources/css/huhwt.min.css in /homepages/20/d313131269/htdocs/webtrees/app/Module/ModuleCustomTrait.php:154 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'filemtime(): st...', '/homepages/20/d...', 154) #1 /homepages/20/d313131269/htdocs/webtrees/app/Module/ModuleCustomTrait.php(154): filemtime('/homepages/20/d...') #2 /homepages/20/d313131269/htdocs/webtrees/modules_v4/huhwt-mtv-master/MultTreeView.php(178): HuHwt\WebtreesMods\MultTreeView->assetUrl('css/huhwt.min.c...') #3 /homepages/20/d313131269/htdocs/webtrees/resources/views/layouts/default.phtml(63): HuHwt\WebtreesMods\MultTreeView->headContent() #4 [internal function]: Fisharebest\Webtrees\View::{closure}(Object(HuHwt\WebtreesMods\MultTreeView), '_huhwt-mtv-mast...') #5 /homepages/20/d313131269/htdocs/webtrees/vendor/illuminate/collections/Collection.php(695): array_map(Object(Closure), Array, Array) #6 /homepages/20/d313131269/htdocs/webtrees/resources/views/layouts/default.phtml(64): Illuminate\Support\Collection->map(Object(Closure)) #7 /homepages/20/d313131269/htdocs/webtrees/app/View.php(183): include('/homepages/20/d...') #8 /homepages/20/d313131269/htdocs/webtrees/app/View.php(278): Fisharebest\Webtrees\View->render() #9 /homepages/20/d313131269/htdocs/webtrees/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make('layouts/default', Array) #10 /homepages/20/d313131269/htdocs/webtrees/app/Http/ViewResponseTrait.php(54): view('layouts/default', Array) #11 /homepages/20/d313131269/htdocs/webtrees/app/Http/RequestHandlers/IndividualPage.php(140): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->viewResponse('individual-page', Array) #12 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/RequestHandler.php(54): Fisharebest\Webtrees\Http\RequestHandlers\IndividualPage->handle(Object(Nyholm\Psr7\ServerRequest)) #13 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #14 /homepages/20/d313131269/htdocs/webtrees/modules_v4/faces/src/Modules/FacesModule.php(98): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #15 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #16 /homepages/20/d313131269/htdocs/webtrees/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #17 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #18 /homepages/20/d313131269/htdocs/webtrees/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #20 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckCsrf->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #22 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #23 /homepages/20/d313131269/htdocs/webtrees/app/Webtrees.php(269): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #24 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/Router.php(153): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #25 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\Router->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #26 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/BootModules.php(60): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BootModules->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #28 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/RegisterGedcomTags.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #29 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RegisterGedcomTags->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #30 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/LoadRoutes.php(75): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\LoadRoutes->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #32 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/CheckForNewVersion.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #33 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForNewVersion->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #34 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/UseTransaction.php(45): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /homepages/20/d313131269/htdocs/webtrees/vendor/illuminate/database/Concerns/ManagesTransactions.php(29): Fisharebest\Webtrees\Http\Middleware\UseTransaction::Fisharebest\Webtrees\Http\Middleware\{closure}(Object(Illuminate\Database\MySqlConnection)) #36 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/UseTransaction.php(46): Illuminate\Database\Connection->transaction(Object(Closure), 3) #37 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTransaction->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #38 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/DoHousekeeping.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #39 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\DoHousekeeping->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #40 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/UseTheme.php(69): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #41 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseTheme->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #42 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/CheckForMaintenanceMode.php(51): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #44 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/UseLanguage.php(71): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #45 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #46 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/UseSession.php(78): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #47 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #48 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/UpdateDatabaseSchema.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #49 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #50 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/UseDatabase.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #51 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #52 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/BadBotBlocker.php(233): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #53 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #54 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/CompressResponse.php(73): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #55 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #56 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/ContentLength.php(40): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #57 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #58 /homepages/20/d313131269/htdocs/webtrees/vendor/middlewares/client-ip/src/ClientIp.php(65): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #59 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/ClientIp.php(47): Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #60 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #61 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/HandleExceptions.php(90): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #62 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #63 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/BaseUrl.php(79): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #64 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #65 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/ReadConfigIni.php(68): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #66 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #67 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/SecurityHeaders.php(48): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #68 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #69 /homepages/20/d313131269/htdocs/webtrees/app/Http/Middleware/EmitResponse.php(57): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #70 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher)) #71 /homepages/20/d313131269/htdocs/webtrees/vendor/oscarotero/middleland/src/Dispatcher.php(118): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #72 /homepages/20/d313131269/htdocs/webtrees/app/Webtrees.php(269): Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #73 /homepages/20/d313131269/htdocs/webtrees/app/Webtrees.php(256): Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest), Array) #74 /homepages/20/d313131269/htdocs/webtrees/index.php(51): Fisharebest\Webtrees\Webtrees->httpRequest() #75 {main}

**Comment by huhwt** [comment]
Hm, the problem seems to be that you have downloaded the full Github repository... that's a development version, not for production use but only for deployment. For production please use the zip file from the current release (https://github.com/huhwt/huhwt-mtv/releases/download/v2.1.4.0.2/huhwt-mtv-2.1.4.0.2.zip), that can be simply unpacked into the modules_v4 directory, then it will run properly.
Greetings
huhwt

**Comment by geugeu1** [comment]
Tanks very much.
