### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by woschla** [huhwt/huhwt-mtv#21]
i get an 500 error after installing the module
my webtrees version is 2.1.5

**Comment by huhwt** [comment]
Hm, may it be you have downloaded the full Github repository? ... that's a development version, not for production use but only for deployment. For production please use the zip file from the current release (https://github.com/huhwt/huhwt-mtv/releases/download/v2.1.4.0.2/huhwt-mtv-2.1.4.0.2.zip), that can be simply unpacked into the modules_v4 directory, then it will run properly.
Greetings
huhwt
