### ISSUE TITLE
Error módulo 2.1.4.0.2

### ISSUE THREAD

**Issue by BernatBanyuls** [huhwt/huhwt-mtv#22]
**It has been some time since I needed to use the module. Today I did and webtrees returned the following problem:**
!
Call to undefined method Fisharebest\Webtrees\Age::ageAtEvent() …/modules_v4/huhwt-mtv/Http/RequestHandlers/MultTreeViewRH.php:85
#0 …/modules_v4/huhwt-mtv/Http/RequestHandlers/MultTreeViewRH.php(203): HuHwt\WebtreesMods\Http\RequestHandlers\MultTreeViewRH->chartTitle(Object(Cissee\WebtreesExt\IndividualExt))
#1 …/app/Http/Middleware/RequestHandler.php(54): HuHwt\WebtreesMods\Http\RequestHandlers\MultTreeViewRH->handle(Object(Nyholm\Psr7\ServerRequest))
#2 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\RequestHandler->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#3 …/modules_v4/reminder/src/Modules/ReminderModule.php(97): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#4 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Reminder\Modules\ReminderModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#5 …/modules_v4/vesta_research_suggestions/ResearchSuggestionsModule.php(277): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#6 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Cissee\Webtrees\Module\ResearchSuggestions\ResearchSuggestionsModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#7 …/modules_v4/faces/src/Modules/FacesModule.php(94): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#8 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): UksusoFF\WebtreesModules\Faces\Modules\FacesModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#9 …/app/Module/HitCountFooterModule.php(154): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#10 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\HitCountFooterModule->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#11 …/app/Module/CheckForNewVersion.php(115): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#12 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Module\CheckForNewVersion->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#13 …/app/Http/Middleware/AuthManager.php(54): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))
#14 …/vendor/oscarotero/middleland/src/Dispatcher.php(136): Fisharebest\Webtrees\Http\Middleware\AuthManager->process(Object(Nyholm\Psr7\ServerRequest), Object(Middleland\Dispatcher))
#15 …/app/Http/Middleware/CheckCsrf.php(80): Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest))

**He borrado y reinstalado el módulo, pero ahora no puedo abrir ni la web. Recibo este problema.**

ErrorException: filemtime(): stat failed for /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/modules_v4/huhwt-mtv/resources/css/huhwt.min.css in /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/app/Module/ModuleCustomTrait.php:154 Stack trace: #0 [internal function]: Fisharebest\Webtrees\Webtrees::Fisharebest\Webtrees\{closure}(2, 'filemtime(): st...', '/var/www/vhosts...', 154, Array) #1 /var/www/vhosts/39868524. servicio-online.net/quiesquiacalp.es/webtrees/app/Module/ModuleCustomTrait.php(154): filemtime('/var/www/vhosts...') #2 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/modules_v4/huhwt-mtv/MultTreeView.php(178): HuHwt\WebtreesMods\MultTreeView->assetUrl('css/huhwt.min.c...') #3 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml(64) : HuHwt\WebtreesMods\MultTreeView->headContent() #4 [función interna]: Fisharebest\Webtrees\View::{closure}(Object(HuHwt\WebtreesMods\MultTreeView), '_huhwt-mtv_') #5 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/vendor/illuminate/collections/Collection.php(695): array_map(Object(Closure), Array, Array) #6 /var/www/vhosts/39868524. servicio-online.net/quiesquiacalp.es/webtrees/modules_v4/vesta_classic_look_and_feel/resources/views/layouts/default.phtml(65): Illuminate\Support\Collection->map(Object(Closure)) #7 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/app/View.php(183): include('/var/www/vhosts...') #8 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/app/View.php(278): Fisharebest\Webtrees\View->render() #9 /var/www/vhosts/ 39868524.servicio-online.net/quiesquiacalp.es/webtrees/app/Helpers/functions.php(145): Fisharebest\Webtrees\View::make('layouts/default', Array) #10 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/app/Http/ViewResponseTrait.php(54): view('layouts/default', Array) #11 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/app/Http/RequestHandlers/UserPage.php(84): Fisharebest\Webtrees\Http\RequestHandlers\UserPage- >viewResponse('user-page', Array) #12 /var/www/vhosts/39868524.servicio-online.net/quiesquiacalp.es/webtrees/app/Http/Middleware/RequestHandler.php(54):

**Necesito su ayuda. Posiblemente, estaré haciendo algo mal, pero no sé cómo solucionarlo. El módulo me resultaba muy útil cuando lo necesitaba. Gracias.**

Webtrees 2.1.7
Modulo: HUHWT-MTV-2.1.4.0.2

**Comment by huhwt** [comment]
Sorry about the inconvinience ... but for me - wt 2.1.7 + huhwt-mtv 2.1.4.0.2 - is all working fine ... the problem you complain about is fixed since version 2.1.1.0.1 ... please remove huhwt-mtv completely and pull the latest release again, then everything should be fine.
