### ISSUE TITLE
Funcionamiento incompleto en la presentación de gráficos <Interactive check>

### ISSUE THREAD

**Issue by BernatBanyuls** [huhwt/huhwt-mtv#23]
Utilizo la versión de webtrees 2.1.16 y la última actualización del módulo. 
Cuando hago una consulta de duplicados y utilizo en módulo, me aparece de la siguiente forma:

![image](https://github.com/huhwt/huhwt-mtv/assets/103060233/061b2af8-6834-45bc-9caf-c0f7935193c0)

Hace algún tiempo, el módulo funcionaba perfectamente. No puedo precisar si era en la misma versión o una anterior.

![Check tree of Juan Ivars Crespo (X2402), 1908– i 3 pàgines més_ Personal - Micro](https://github.com/huhwt/huhwt-mtv/assets/103060233/9338e20b-5fc6-4b5c-85b2-3f6926b412e7)

**Comment by huhwt** [comment]
The last version is from December 2022... and then the changes didn't affect the features themselves. To be honest I can't see any significant difference in the screenshots either - what seems to have changed somehow?

**Comment by BernatBanyuls** [comment]
Antes, los árboles se presentaban igual que el “árbol interactivo” de webtrees, Es de cir, así:

 



 

Y ahora...

 



 

Lo que faltan son las líneas de marcos y la separación entre ellos.

 

Gracias por ayudar.

 

 

Abans d'imprimir aquest correu, penseu si és necessari.

Aquest correu electrònic pot contenir informació confidencial o legalment protegida i està exclusivament adreçat a la persona o entitat destinatària. Si no sou el destinatari final o la persona encarregada de recollir-lo, no esteu autoritzat a llegir-lo, retenir-lo, modificar-lo, distribuir-lo, copiar-lo ni a revelar-ne el contingut. Si heu rebut aquest correu electrònic per error, us preguem que informeu el remitent i elimineu del vostre sistema el missatge i el material annex que pugui contenir. 
Gràcies per la vostra col·laboració.

 

De: EW.H ***@***.***> 
Enviat: dijous, 6 de juliol de 2023 0:24
Per a: huhwt/huhwt-mtv ***@***.***>
A/c: BernatBanyuls ***@***.***>; Author ***@***.***>
Tema: Re: [huhwt/huhwt-mtv] Funcionamiento incompleto en la presentación de gráficos <Interactive check> (Issue #23)

 

The last version is from December 2022... and then the changes didn't affect the features themselves. To be honest I can't see any significant difference in the screenshots either - what seems to have changed somehow?

**Comment by huhwt** [comment]
I'm sorry, there are no pictures included, I don't understand the problem. In my system, everything looks as usual and desired to me. Maybe delete the module completely and download the current release from Github.

**Comment by BernatBanyuls** [comment]
Gracias por tu ayuda.

 

Sí. Tenia pensado reinstalar el módulo (antiguamente funcionaba correctamente). Estoy teniendo problemas en mi acceso al servidor. Tan pronto Greg me pueda ayudar, es lo primero que haré y veremos el resuiltado.

 

Respecto a las imágenes, creía que ya habías visto las que publique en el foro. De todos mdos, aquí te paso otras.

 



 





 

Abans d'imprimir aquest correu, penseu si és necessari.

Aquest correu electrònic pot contenir informació confidencial o legalment protegida i està exclusivament adreçat a la persona o entitat destinatària. Si no sou el destinatari final o la persona encarregada de recollir-lo, no esteu autoritzat a llegir-lo, retenir-lo, modificar-lo, distribuir-lo, copiar-lo ni a revelar-ne el contingut. Si heu rebut aquest correu electrònic per error, us preguem que informeu el remitent i elimineu del vostre sistema el missatge i el material annex que pugui contenir. 
Gràcies per la vostra col·laboració.

 

De: EW.H ***@***.***> 
Enviat: dilluns, 10 de juliol de 2023 17:58
Per a: huhwt/huhwt-mtv ***@***.***>
A/c: BernatBanyuls ***@***.***>; Author ***@***.***>
Tema: Re: [huhwt/huhwt-mtv] Funcionamiento incompleto en la presentación de gráficos <Interactive check> (Issue #23)

 

I'm sorry, there are no pictures included, I don't understand the problem. In my system, everything looks as usual and desired to me. Maybe delete the module completely and download the current release from Github.

**Comment by BernatBanyuls** [comment]
En estas fechas (por fin) he podido solucionar mis problmeas de acceso al servidor y una vez actualizado webrtrees (2.1.17) he borrado y reintaladdo tu módulo. 
![image](https://github.com/huhwt/huhwt-mtv/assets/103060233/b4927f79-160b-481d-a76b-2c7e94ea2852)
![image](https://github.com/huhwt/huhwt-mtv/assets/103060233/c65898fe-888a-4048-aff6-d08f9099a10c)

He vueto a entrar en [interactive check] y mi visualización sigue igual. Ahora aparecen los gràficos así (no hagas caso de las flechas y recuadros)
![image](https://github.com/huhwt/huhwt-mtv/assets/103060233/fe2213b3-1cb0-460b-bde3-81d28d29c266)
Cuando yo recuerdo que su presentación era similar( o igual) a esta:
![image](https://github.com/huhwt/huhwt-mtv/assets/103060233/452d5f55-8fb3-4b25-866c-ba8ae24773ff)

Siguiente cuestión!
El módulo me dice que tengo SEIS duplicados, pero investigando observo que son personas diferentes.  
![image](https://github.com/huhwt/huhwt-mtv/assets/103060233/5019bb7f-437d-4434-9bc6-a3d138fc520c)

Esto en principio, no es importante y me gusta que me "advierta" de posibles duplicados, pero una vez investigados, me gustaría quitarlos de la relación inicial
![image](https://github.com/huhwt/huhwt-mtv/assets/103060233/128ab9a5-0966-4ca6-ae0d-d941636ec6ca)

y no sé cómo hacerlo. He probado algunoss recursos, pero ninguna funciona y voy arrastrando desde hace meses esa lista de "duplicados". He tenido que anotarlos en un fichero y comprobar si hay alguno nuevo, pero claro, esto es muy laborioso. Quizás puedas aconsejarme de alguna solución. Gracias.

Si necesitas que amplie algunos datos o que haga alguna prueba, ya me lo dices. Me sabe mal molestarte, pero es un módulo muy práctico para mi (tengo 16000 registros).

Gracias por tu trabajo.

**Comment by huhwt** [comment]
Ich habe jetzt die aktuelle Version mit in die Anzeige aufgenommen, in der Anzeige einer doppelten Person sollte jetzt also "V-2.1.17" erscheinen. Wenn auch diese Version immer noch Probleme macht ... habe ich so gar keine Idee, woran das dann liegen könnte. Wie gesagt, bei mir funktioniert alles so, wie gedacht und gewünscht.

Zur zweiten Frage:
Doubletten werden über den Abgleich von Ereignissen zu Personen ermittelt. Beim Import des GEDcom in Webtrees werden die Dateninhalte auf diverse Tabellen verteilt. Ereignisse sind im GEDcom durch spezielle TAGs gekennzeichnet, diesen sind jeweils ein Ereignisdatum zugeordnet. In Webtrees werden diese Inhalte in der Tabelle wt_dates abgelegt, dem Datum wird die TAG-Kennung des Ereignisses als d_fact beigegeben. Personen haben Namen, diese werden in Webtrees in der Tabelle wt_name abgelegt. In beiden Tabellen stehen zu jedem Eintrag auch die XREFs, so dass differenziert werden kann, welcher Person-ID der Eintrag zugerechnet werden soll. Der Abgleich erfolgt durch Analyse, welche Ereignisse mit gleichem Datum bei welchen Personen mit gleichem Namen stattgefunden haben, diese werden dann als potentielle Doublette ausgegeben.

Und hier wird es schwierig. Jedes beliebige Event mit Datum ist in wt_dates gelistet. Und als Eintrag in wt_name wird nicht nur das offizielle NAME-TAG übernommen, sondern auch TAGs wie _MARNM oder _AKA, welche als legacy oder individuell deklariert sind. Die Inhalte dieser TAGs sind nicht so signifikant wie der Inhalt des NAME-TAG - da steht ja der komplette Personenname mit allen Bestandteilen drin. Wenn also alle beliebigen Ereignisse mit nicht differenzierten Namen in Bezug gebracht werden, ist die Wahrscheinlichkeit sehr hoch, dass im Ergebnis Ungereimtheiten auftreten - Garbage in, Garbage out.

Tatsächlich war dieser Umstand der Auslöser, dass ich das Modul MultiTreeview gebaut habe, weil ich dachte, dass eine mehrere Generationen überspannende Ansicht mir helfen würde zu verstehen, welcher Zweig einer Doublette eigentlich der relevante und welcher eventuell zu verwerfen wäre oder ob ich 2 Personeneinträge verschmelzen könnte bzw. sollte.

In meinem Datenbestand von ca. 9500 Einträgen habe ich nämlich mehr als 100 Doubletten gemeldet bekommen - Respekt, dass Sie nur 6 bei mehr als 16000 Einträgen haben.

Ein gewisse Schärfung des Ergebnisses habe ich durch eine zusätzliche Klausel in der grundlegenden Abfrage im Modul 'app/Services/AdminService.php' erreicht, dieses ist im README.md beschrieben. Durch Einschränkung der Abfrage auf solche Einträge, welche nur das NAME-TAG enthalten, sind es weniger Doubletten-Meldungen geworden. Eine weitere Verringerung ergibt sich, wenn nur relevante Events gefiltert werden, das wären BIRT, CHR, BAPM, DEAT, BURI als Inhalte des Feldes d_fact in wt_dates.
Ich arbeite aktuell an der Erweiterung des Moduls dahingehend, dass es möglich sein wird, diese Verschärfungen als Konfigurations-Optionen ein- und auszuschalten, also nicht mehr in den Source-Code der Original-Funktion eingreifen zu müssen.

Fazit:
Wenn die Version v2.1.17.0 immer noch die beschriebenen Layout-Probleme aufzeigt, kann ich nicht wirklich helfen, für mich funktioniert das Layout mit allen bei mir installierten Themes - neben den Standards wären das noch justLight und modern - und allen Browsern - Firefox, Chrome, Edge, Brave. Haben Sie eigentlich auch mal mein Modul huhwt-xtv ausprobiert? Das ist das Interaktive Treeview für eine Einzelperson mit diversen Erweiterungen und unabhängigem CSS, hat das bei Ihnen auch Layout-Probleme?

Die Doubletten-Analyse hat gewisse Schwächen, ich arbeite daran, es etwas präziser und flexibler zu machen. Es gibt trotzdem Situationen, in denen Doubletten fäschlicherweise gemeldet werden, wie es wohl auch Situationen geben mag, wo durch die doch recht triviale Datenanalyse nicht erkannt werden kann, dass 2 Identitäten in Webtrees tatsächlich die gleiche Person beschreiben, einfach weil die hinterlegten Ereignisse bei den Identitäten mit unterschiedlichen Zeitangaben gesetzt sind. Wird eine Doublette gemeldet, kommt man nicht umhin, sich detailliert mit den einzelnen Ereignissen auseinander zu setzen. Stellt sich heraus, dass es sich wirklich um 2 verschiedene Personen handelt, muss man sich damit abfinden, dass bei jeder folgenden Analyse diese Personen immer wieder erscheinen werden - sozusagen "gute alte Bekannte" werden.

**Comment by BernatBanyuls** [comment]
Saludos y mcuhas gracias por tu completa respuesta.
1º- He reinstalado nuevamente el módulo y mi problema sigue presente.
2º He instalado HUHWT-XTV y funciona perfectamente. Nódulo y gráficos Además, me parece muy útil y lamento no haberlo conocido con anterioridad.  (Aunque no he hallado todavía dónde están los menús de configuración. Seguiré buscando :-) )
3º Por cierto, si necesitas que lo traduzca al catalán o al español, dímelo y muy gusoto te ayudaría.
4º La fórmula para encontrar duplicados me parece correcta (inentataré comprenderla mejor cuando tenga un poco de tiempo) y, como comenté, no me preocupa que me generen duplicados dudosos. Lo agradezco.
5º En meses anteriores, el módulo de duplicados funcionaba correctamente y los gráficos erran correctos. Cuando desaparecieron pensé que sería de una actualición de webtrees , puesto que en mi ordenador no he efectuado ninguca correción o añadido (que sea consciente, claro)

De todos modos, puedes cerrar el tema ya que me arreglo bien como está y ya vermos cómo funcionan las cosas en un futuro. Reitero mi ofrecimiento para las traducciones y felicitarte por tu dos módulos. Son muy útiles. Gracias.

**Comment by huhwt** [comment]
Hallo und Guten Abend,
Danke, dass Sie den Versuch mit HUHWT-XTV gemacht haben, und ich freue mich sehr, dass es Ihnen gefällt.

Wenn trotz der neuen Version das HUHWT-MTV immer noch die Layout-Probleme hat, muss die Ursache im Umfeld liegen ... welches Betriebssystem hat der Server, welches Betriebssystem hat Ihr Rechner und welchen Browser benutzen Sie?

Die Konfigurations-Option ist nicht in V2.1.17.0 enthalten, ich bin noch dabei, das neue Release V2.1.17.1 zusammenzustellen.

Das großzügige Angebot, sich für Übersetzungen in Spanische und/oder Katalanische zu engagieren, nehme ich mit Begeisterung, Dankbarkeit und in aller Demut an - Allerdings habe ich insgesamt 5 Webtrees-Module am Start 😁, welche alle nicht ins Spanische übersetzt sind  ... Bitte nehmen Sie doch in dieser Angelegenheit wie auch in Bezug auf das MTV-Problem direkten Kontakt mit mir über mein im Profil angegebene Mail-Adresse auf.
