### ISSUE TITLE
installing, how?

### ISSUE THREAD

**Issue by mariannevanharten** [huhwt/huhwt-mtv#30]
"Installation and upgrading
... in the usual way: Download the zip file, unzip it into the modules_v4 directory, and that's it. You should remove the existing version completely before."

What is the usual way? I only see huhwt-mtv-master. Where do I find the file to use in webtrees 2.2.1?

Best regards,
Marianne

**Comment by huhwt** [comment]
https://github.com/huhwt/huhwt-mtv/releases  -  take the zip file from the latest release, titled 'wt22v1 - PHP8.3' ...
