### ISSUE TITLE
User interface

### ISSUE THREAD

**Issue by hartenthaler** [huhwt/huhwt-mtv#5]
... some minor remarks to this nice module:
- maybe you can add in the title both individuals who are compared
- there are sometimes black dots that I do not understand
- it would be helpful if the compared individuals are highlighted in the hourglass diagram
- the internal ids are doubled because I'm using the Vesta-modules, too. Maybe you can avoid adding the id if the id is already there.

![Screenshot (228)_LI](https://user-images.githubusercontent.com/6324175/113411172-65ba3d80-93b5-11eb-8879-3294fca382d2.jpg)

**Comment by huhwt** [comment]
Thanks for the new attempt!
There seems to be something still not quite right - there are somehow missing the references to custom css and js.
This is how a page looks like in my web: -5-screen
and this is how the structure of the page should look in the inspector: -5-inspektor
I will have a look at the interference with the vesta modules.
Happy Easter
EW.H
![#5-screen](https://user-images.githubusercontent.com/73525321/113503752-07679900-9534-11eb-8129-27654db54943.png)
![#5-inspektor](https://user-images.githubusercontent.com/73525321/113503765-223a0d80-9534-11eb-9c49-745e2bcc512d.png)

**Comment by hartenthaler** [comment]
![Screenshot (235)](https://user-images.githubusercontent.com/6324175/113768179-d9df4300-971f-11eb-97bb-3ab994b3409d.png)

**Comment by hartenthaler** [comment]
![Screenshot (235)_LI](https://user-images.githubusercontent.com/6324175/113768275-f4b1b780-971f-11eb-989d-d6712353c00f.jpg)

**Comment by hartenthaler** [comment]
Using version 1.2.1 the doubled xrefs disapeared. Fine! The stylesheet link is still wrong. Maybe you like to add some debug code. I will be happy to test it, because today I had to compare two doubled individuals which was a bit complicated and your tool helped a lot to get very fast a good overview.

![Screenshot (247)_LI](https://user-images.githubusercontent.com/6324175/114408611-e1806b00-9ba9-11eb-8114-64904a80a874.jpg)
